package com.edw.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.4
 * 2024-06-16T21:28:22.047+07:00
 * Generated source version: 4.0.4
 *
 */
@WebServiceClient(name = "EmployeeService",
                  wsdlLocation = "file:wsdl/employee.wsdl",
                  targetNamespace = "http://localhost/employee")
public class EmployeeService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://localhost/employee", "EmployeeService");
    public static final QName EmployeeServiceSOAP = new QName("http://localhost/employee", "EmployeeServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/employee.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EmployeeService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:wsdl/employee.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EmployeeService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EmployeeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public EmployeeService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public EmployeeService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public EmployeeService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns EmployeeServicePortType
     */
    @WebEndpoint(name = "EmployeeServiceSOAP")
    public EmployeeServicePortType getEmployeeServiceSOAP() {
        return super.getPort(EmployeeServiceSOAP, EmployeeServicePortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeServicePortType
     */
    @WebEndpoint(name = "EmployeeServiceSOAP")
    public EmployeeServicePortType getEmployeeServiceSOAP(WebServiceFeature... features) {
        return super.getPort(EmployeeServiceSOAP, EmployeeServicePortType.class, features);
    }

}
